#pragma once

#define MAX_INPUT_LENGTH 100
#define MAX_ARG_LENGTH 50

#define MAX_ITEM_TYPES 100
#define MAX_WEAPON_TYPES 100
#define MAX_ARMOR_TYPES 100

#define MAX_ENEMY_COUNT 10

#define MAX_SKILL_TYPES 50